# Generated by Django 5.0 on 2023-12-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviewsys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=models.TextField(blank=True, max_length=8192),
        ),
    ]
